In [1]:
import numpy as np 

In [3]:
a = np.arange(0,9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [2]:
b = np.ones(9).reshape(3,3)
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
d = np.arange(1,10)

In [14]:
d[(d % 2 != 0)]

array([1, 3, 5, 7, 9])

In [21]:
e = np.arange(1, 10)
e[(e % 2 != 0)] = -1
e


array([-1,  2, -1,  4, -1,  6, -1,  8, -1])

In [24]:
ab = np.ones(12)
ab.reshape(2,6)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [50]:
a = np.random.rand(3,3)
b = np.random.rand(3,3)
c =np.dot(a,b)
d = np.sum(c)
d

9.695746865890825

In [51]:
a = ([[1, 2, 3, 4, 5], [4, 5, 6, 7, 8, 9]])
np.unique(a)


C:\Users\44790\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numpy\lib\arraysetops.py:270: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ar = np.asanyarray(ar)


array([list([1, 2, 3, 4, 5]), list([4, 5, 6, 7, 8, 9])], dtype=object)